import type { DashboardInsightsData } from "@/features/dashboard/lib/dashboard-overview-types";

/** Fixed timestamps so SSR and client hydration stay in sync. */
const PLACEHOLDER_TIMESTAMPS = {
  hours2: "2026-06-18T10:00:00.000Z",
  hours5: "2026-06-18T07:00:00.000Z",
  hours7: "2026-06-18T05:00:00.000Z",
  days1: "2026-06-17T12:00:00.000Z",
  days2: "2026-06-16T12:00:00.000Z",
  days3: "2026-06-15T12:00:00.000Z",
  days4: "2026-06-14T12:00:00.000Z",
  days5Overdue: "2026-06-13T12:00:00.000Z",
  days12Overdue: "2026-06-06T12:00:00.000Z",
} as const;

export function getDashboardPlaceholderInsights(): DashboardInsightsData {
  return {
    recentActivity: [
      {
        id: "act-1",
        actorName: "Anna Kowalska",
        isCurrentUser: false,
        kind: "document_added",
        documentName: "Analiza techniczna.docx",
        workspaceName: "Projekty budowlane",
        occurredAt: PLACEHOLDER_TIMESTAMPS.hours5,
        actor: {
          name: "Anna Kowalska",
          email: "anna@example.com",
          avatarUrl: null,
          avatarPreset: "architect",
        },
      },
      {
        id: "act-2",
        actorName: "Piotr Nowak",
        isCurrentUser: false,
        kind: "request_completed",
        requestTitle: "Porównanie kosztów materiałów",
        occurredAt: PLACEHOLDER_TIMESTAMPS.hours7,
        actor: {
          name: "Piotr Nowak",
          email: "piotr@example.com",
          avatarUrl: null,
          avatarPreset: "engineer",
        },
      },
      {
        id: "act-3",
        actorName: "Ty",
        isCurrentUser: true,
        kind: "document_added",
        documentName: "Oferta inwestycyjna.pdf",
        workspaceName: "Przestrzeń główna",
        occurredAt: PLACEHOLDER_TIMESTAMPS.days2,
        actor: {
          name: "Ty",
          email: "you@example.com",
          avatarUrl: null,
          avatarPreset: "constructor",
        },
      },
      {
        id: "act-4",
        actorName: "Marta Wiśniewska",
        isCurrentUser: false,
        kind: "estimate_sent",
        estimateTitle: "Remont łazienki — wersja 2",
        occurredAt: PLACEHOLDER_TIMESTAMPS.days3,
        actor: {
          name: "Marta Wiśniewska",
          email: "marta@example.com",
          avatarUrl: null,
          avatarPreset: "electrician",
        },
      },
      {
        id: "act-5",
        actorName: "Jan Kowalczyk",
        isCurrentUser: false,
        kind: "document_added",
        documentName: "Kosztorys_Q2_2024.xlsx",
        workspaceName: "Finanse",
        occurredAt: PLACEHOLDER_TIMESTAMPS.days4,
        actor: {
          name: "Jan Kowalczyk",
          email: "jan@example.com",
          avatarUrl: null,
          avatarPreset: "accountant",
        },
      },
    ],
    recentDocuments: [
      {
        id: "doc-1",
        fileName: "Oferta inwestycyjna.pdf",
        fileType: "PDF",
        workspaceName: "Przestrzeń główna",
        fileSizeBytes: 2_516_582,
        occurredAt: PLACEHOLDER_TIMESTAMPS.hours2,
      },
      {
        id: "doc-2",
        fileName: "Analiza techniczna.docx",
        fileType: "DOCX",
        workspaceName: "Projekty budowlane",
        fileSizeBytes: 1_782_336,
        occurredAt: PLACEHOLDER_TIMESTAMPS.hours5,
      },
      {
        id: "doc-3",
        fileName: "Kosztorys_Q2_2024.xlsx",
        fileType: "XLSX",
        workspaceName: "Finanse",
        fileSizeBytes: 3_251_840,
        occurredAt: PLACEHOLDER_TIMESTAMPS.days1,
      },
      {
        id: "doc-4",
        fileName: "Prezentacja_mieszkanie.pptx",
        fileType: "PPTX",
        workspaceName: "Mieszkanie",
        fileSizeBytes: 6_502_400,
        occurredAt: PLACEHOLDER_TIMESTAMPS.days3,
      },
    ],
    overduePayments: [
      {
        id: "pay-1",
        estimateId: "est-1",
        estimateTitle: "Remont łazienki — etap I",
        dueDate: PLACEHOLDER_TIMESTAMPS.days12Overdue,
        amount: 12_480,
        currency: "PLN",
        customerName: "Anna Kowalska",
      },
      {
        id: "pay-2",
        estimateId: "est-2",
        estimateTitle: "Instalacja fotowoltaiki",
        dueDate: PLACEHOLDER_TIMESTAMPS.days5Overdue,
        amount: 9_637.8,
        currency: "PLN",
        customerName: "Piotr Nowak",
      },
      {
        id: "pay-3",
        estimateId: "est-3",
        estimateTitle: "Malowanie biura — faktura końcowa",
        dueDate: PLACEHOLDER_TIMESTAMPS.days2,
        amount: 6_000,
        currency: "PLN",
        customerName: "Studio Architektura Sp. z o.o.",
      },
    ],
  };
}
