export const ESTIMATE_TEMPLATE_MAX_SECTIONS = 20;
export const ESTIMATE_TEMPLATE_MAX_ITEMS_PER_SECTION = 20;
export const ESTIMATE_TEMPLATE_NAME_MAX_LENGTH = 120;
export const ESTIMATE_TEMPLATE_DESCRIPTION_MAX_LENGTH = 500;
export const ESTIMATE_TEMPLATE_SECTION_TITLE_MAX_LENGTH = 120;
export const ESTIMATE_TEMPLATE_ITEM_NAME_MAX_LENGTH = 160;
export const ESTIMATE_TEMPLATE_GUIDANCE_MAX_LENGTH = 300;
