export const PRICE_LIST_MAX_ITEMS = 200;
export const PRICE_LIST_NAME_MAX_LENGTH = 120;
export const PRICE_LIST_ITEM_NAME_MAX_LENGTH = 160;
export const PRICE_LIST_UNIT_MAX_LENGTH = 24;
export const PRICE_LIST_NOTE_MAX_LENGTH = 300;
export const PRICE_LIST_CURRENCY_LENGTH = 3;
